---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authors":
    get:
      summary: All Authors
      tags:
      - Authors
      responses:
        '200':
          description: Authors List
          content: {}
    post:
      summary: Create an Author
      tags:
      - Authors
      parameters: []
      responses:
        '201':
          description: author created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
              required:
              - first_name
              - last_name
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
